In [1]:
import numpy as np
from numpy import linalg as LA
from math import sqrt

In [2]:
A = np.array([(4, -3), (2, -1)])
print(A)

[[ 4 -3]
 [ 2 -1]]


In [3]:
Asquared = A @ A
print(Asquared)

[[10 -9]
 [ 6 -5]]


In [4]:
Afourth = Asquared @ Asquared
print(Afourth)

[[ 46 -45]
 [ 30 -29]]


In [5]:
Aeighth = Afourth @ Afourth
print(Aeighth)

[[ 766 -765]
 [ 510 -509]]


Lorsque A est diagonalisable, et que l’exposant est grand, on peut la diagonaliser puis calculer l’exposant.

Calculons $A = E D E^{-1}$.

In [6]:
E1 = np.array([3.0/sqrt(13), 2.0/sqrt(13)])
E2 = np.array([1.0/sqrt(2), 1.0/sqrt(2)])
print(E1)
print(E2)

[0.83205029 0.5547002 ]
[0.70710678 0.70710678]


In [7]:
print(A @ E1)
print(A @ E2)

[1.66410059 1.10940039]
[0.70710678 0.70710678]


In [8]:
Et = np.array([E1, E2])
print(Et)
E = Et.transpose()
print(E)

[[0.83205029 0.5547002 ]
 [0.70710678 0.70710678]]
[[0.83205029 0.70710678]
 [0.5547002  0.70710678]]


In [9]:
Einv = LA.inv(E)
print(Einv)

[[ 3.60555128 -3.60555128]
 [-2.82842712  4.24264069]]


In [10]:
D = np.array([(2, 0), (0, 1)])
print(D)

[[2 0]
 [0 1]]


In [11]:
E @ D @ Einv

array([[ 4., -3.],
       [ 2., -1.]])

In [12]:
e1 = np.array([1, 0])
e2 = np.array([0, 1])
print(e1)
print(e2)

[1 0]
[0 1]


In [13]:
D8 = LA.matrix_power(D, 8)
print(D8)

[[256   0]
 [  0   1]]


In [14]:
E @ D8 @ Einv

array([[ 766., -765.],
       [ 510., -509.]])