In [1]:
import numpy as np
from numpy import linalg as LA
from math import sqrt

In [2]:
u1 = np.array([2, 5, -1])
u2 = np.array([-2, 1, 1])
y = np.array([1, 2, 3])
print(u1, u2, y)

[ 2  5 -1] [-2  1  1] [1 2 3]


In [3]:
yOnS = 3.0/10.0 * u1 + 1.0/2.0 * u2
print(yOnS)
yleft = y - yOnS
print(yleft)

[-0.4  2.   0.2]
[1.4 0.  2.8]


In [4]:
v = np.cross(u1, u2)
print(v)

[ 6  0 12]


In [5]:
y @ v

42

In [6]:
yOnVOrth = 42 / 180 * v
print(yOnVOrth)

[1.4 0.  2.8]


In [7]:
u1Normed = u1 / LA.norm(u1)
u2Normed = u2 / LA.norm(u2)
vNormed = v / LA.norm(v)
vNormedAlt = np.cross(u1Normed, u2Normed)
Pall = np.array([u1Normed, u2Normed, vNormed])
newBasis = Pall.transpose()
print(newBasis)
print(vNormedAlt)

[[ 0.36514837 -0.81649658  0.4472136 ]
 [ 0.91287093  0.40824829  0.        ]
 [-0.18257419  0.40824829  0.89442719]]
[0.4472136  0.         0.89442719]


In [8]:
newBasis @ newBasis.transpose()

array([[ 1.00000000e+00, -1.11022302e-16, -1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00,  5.55111512e-17],
       [-1.11022302e-16,  5.55111512e-17,  1.00000000e+00]])

In [9]:
PS = np.array([u1Normed, u2Normed])
print(PS)

[[ 0.36514837  0.91287093 -0.18257419]
 [-0.81649658  0.40824829  0.40824829]]


In [10]:
PS @ y

array([1.64316767, 1.22474487])

In [11]:
Pall @ y

array([1.64316767, 1.22474487, 3.13049517])

In [12]:
D = np.diag([1/sqrt(30), 1/sqrt(6), 1/sqrt(180)])
print(D)

[[0.18257419 0.         0.        ]
 [0.         0.40824829 0.        ]
 [0.         0.         0.0745356 ]]


In [13]:
D @ Pall @ y

array([0.3       , 0.5       , 0.23333333])