In [6]:
import numpy as np
import numpy.linalg as LA

In [7]:
u1 = np.array([5, -2, 1])
u2 = np.array([1, 2, -1])
y = np.array([-1, -5, 10])
print(u1)
print(u2)
print(y)

[ 5 -2  1]
[ 1  2 -1]
[-1 -5 10]


In [8]:
u1 @ u2

0

In [9]:
y @ u1

15

In [10]:
y @ u2

-21

In [11]:
LA.norm(u1)

5.477225575051661

In [12]:
LA.norm(u2)

2.449489742783178

In [14]:
yOnV = 15/30 * u1 + -21/6 * u2
print(yOnV)

[-1. -8.  4.]


In [17]:
d = y - yOnV
print(d)

[0. 3. 6.]


In [19]:
d @ u1

0.0

In [20]:
d @ u2

0.0