In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
u1 = np.array([5, -2, 1])
u2 = np.array([1, 2, -1])
y = np.array([-1, -5, 10])
M = np.diag([1, 2, 1])
print(u1)
print(u2)
print(y)
print(M)

[ 5 -2  1]
[ 1  2 -1]
[-1 -5 10]
[[1 0 0]
 [0 2 0]
 [0 0 1]]


In [3]:
u1CrossU2InM = np.cross(M @ u1, M @ u2)
print(u1CrossU2InM)

[ 0  6 24]


In [4]:
yOnOrth = (y @ M @ u1CrossU2InM) / (u1CrossU2InM @ M @ u1CrossU2InM) * u1CrossU2InM
print(3*yOnOrth)

[ 0.  5. 20.]


In [5]:
distSquared = yOnOrth @ M @ yOnOrth
print(distSquared)

50.00000000000001


In [6]:
u1 @ M @ u2

-4

In [7]:
u2OnU1 = (u1 @ M @ u2) / (u1 @ M @ u1) * u1
print(17*u2OnU1)

[-10.   4.  -2.]


In [8]:
b2 = u2 - u2OnU1
print(17*b2)
print(b2 @ M @ u1)

[ 27.  30. -15.]
4.440892098500626e-16


In [9]:
yOnU1 = (y @ M @ u1) / (u1 @ M @ u1) * u1
print(34*yOnU1)

[125. -50.  25.]


In [10]:
#print((17*b2) @ M @ (17*b2))
yOnB2 = (y @ M @ b2) / (b2 @ M @ b2) * b2
#print(2754*yOnB2)
print(yOnB2)

[-4.67647059 -5.19607843  2.59803922]


In [11]:
yOnV = yOnU1 + yOnB2
print(yOnV)

[-1.         -6.66666667  3.33333333]


In [12]:
yOnOrth = y - yOnV
print(yOnOrth)

[0.         1.66666667 6.66666667]


In [13]:
print(yOnOrth @ M @ u1)
print(yOnOrth @ M @ b2)

-1.7763568394002505e-15
1.7763568394002505e-15


In [14]:
print(yOnOrth @ M @ y)

49.999999999999986
