In [18]:
from math import sqrt
import numpy as np
import numpy.linalg as LA

In [3]:
A = np.array([(1, 3, 3), (-3, -5, -3), (3, 3, 1)])
print(A)

[[ 1  3  3]
 [-3 -5 -3]
 [ 3  3  1]]


In [28]:
L = np.diag([1, -2, -2])
print(L)

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [40]:
EV1 = np.array([1, -1, 1])
print(A @ EV1, "=", 1*EV1)

[ 1 -1  1] = [ 1 -1  1]


In [41]:
EV2 = np.array([1, 0, -1])
print(A @ EV2, "=", -2*EV2)

[-2  0  2] = [-2  0  2]


In [42]:
EV3 = np.array([1, -2, 1])
print(A @ EV3, "=", -2*EV3)

[-2  4 -2] = [-2  4 -2]


In [43]:
E = np.array([EV1, EV2, EV3]).transpose()
print(E)

[[ 1  1  1]
 [-1  0 -2]
 [ 1 -1  1]]


In [48]:
print(A @ E, "\n=\n", E @ L)

[[ 1 -2 -2]
 [-1  0  4]
 [ 1  2 -2]] 
=
 [[ 1 -2 -2]
 [-1  0  4]
 [ 1  2 -2]]


In [50]:
Einv = LA.inv(E)
print(Einv)
print(Einv @ E, "= I")
print(E @ L @ Einv, "= A")

[[ 1.   1.   1. ]
 [ 0.5  0.  -0.5]
 [-0.5 -1.  -0.5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I
[[ 1.  3.  3.]
 [-3. -5. -3.]
 [ 3.  3.  1.]] = A
